dotfiles=$HOME/.dotfiles
zprezto=$HOME/.zprezto

#
# Aliases
#

alias v='mvim'

# Editing config files
alias ve='v $dotfiles/vim/vimrc'
alias ze='v $dotfiles/zsh/zshrc'
alias zpe='v $HOME/.zpreztorc'
alias ge='v $dotfiles/git/gitconfig'
alias he='sudo vim /etc/hosts'

# Reload settings
alias zr='source $dotfiles/zsh/zshrc'

# Show me files matching "ls ag"
alias lsf='ll | ag'

# PS
alias psa='ps aux'
alias psg='ps aux | ag '
alias psr='ps aux | ag ruby'

# Common shell functions
alias tf='tail -f'
alias lh='ls -alt | head' # see the last modified files
alias cl='clear'

# Zippin
alias gzc='tar -zcvf'
alias gzx='tar -zxvf'

# Kill
alias ka9='killall -9'
alias k9='kill -9'

# Editor
export EDITOR=vim

# Node binaries
# PATH=$PATH:/usr/local/share/npm/bin

# Boxen
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Android SDK
export ANDROID_HOME=/opt/boxen/homebrew/opt/android-sdk

# added by travis gem
[ -f /Users/dcal/.travis/travis.sh ] && source /Users/dcal/.travis/travis.sh
